### ISSUE TITLE
Ask for login from time to time

### ISSUE THREAD

**Issue by lxg208** [jellyfin/jellycon#112]
JellyCon always ask me to login from time to time, is there a way to keep it login?

**Comment by mcarlton00** [comment]
Check your addon settings and verify that "Show change user dialog" is disabled under Addons -> Jellycon -> Addon Actions -> Show addon settings -> Events.  It'll be near the bottom in the screensaver section.

**Comment by lxg208** [comment]
Thank you, this works.
