### ISSUE TITLE
Viewing Movie Featurettes 

### ISSUE THREAD

**Issue by Necronar** [jellyfin/jellycon#115]
Maybe I'm missing it, but is there currently a way to watch the featurettes/bts/delete scenes? If not, is this something that is being considered or that I can fix on my end alone?

**Comment by mcarlton00** [comment]
If you open the context menu on an item and scroll down a few entries, there should be an option saying 'Show Extras'.  Does that get you what you want?  Based on the code it looks like it's only available for movies currently.

**Comment by Necronar** [comment]
Ah yes. Thank you. For some reason it wasn't working. I updated Kodi and reinstalled Jellycon. Everything seems to be good now and shows up as intended.
