### ISSUE TITLE
Show title is nowhere to be found in Next Up/Continue

### ISSUE THREAD

**Issue by ltGuillaume** [jellyfin/jellycon#116]
As far as I can see, when going to Next Up/Continue watching, the show name is nowhere to be found in that screen (using the default Kodi skin Estuary).

I think that titles like `Show name 1x01` would make more sense than just the episode title. Now, when the screenshot is unclear, it's just guesswork of what show we're talking about until you press `I` for more info. InfoWall or WideList view don't show the show's title either.

**Comment by mcarlton00** [comment]
There's an option in the settings under "Interface" that indicates the episode format.  The widgets will respect that setting after the next release, so there's some customability to it.

**Comment by ltGuillaume** [comment]
Looking forward to that!
