### ISSUE TITLE
Kodi translatePath deprecated

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellycon#129]
This error is reported in the logs a lot.
```
xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
```

`xbmcvfs.translatePath` is not available on Kodi 18 and below, so we need to do a wrapper to route to the right function based on version.

**Comment by oddstr13** [comment]
Oh, I like these!
