### ISSUE TITLE
Error notification immediately when stopping a video

### ISSUE THREAD

**Issue by baconsalad** [jellyfin/jellycon#142]
Get this error every time when stopping a video

`2022-04-19 01:41:14.570 T:865      INFO <general>: JELLYFIN.resources.lib.downloadutils -> ERROR::resources/lib/downloadutils.py:708 HTTP response error for {jellyfin-server}/Videos/ActiveEncodings?DeviceId=45398342095843209850934850984345: 400 b'{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-45398453095439087549875879457548-4039840938409384-00","errors":{"playSessionId":["The playSessionId field is required."]}}'`

problem line in resources/lib/play_utils.py
`url = "{server}/Videos/ActiveEncodings?DeviceId=%s" % device_id`

fixed by changing to
`url = "{server}/Videos/ActiveEncodings?DeviceId=%s&playSessionId=%s" % (device_id, play_session_id)`

**Comment by mcarlton00** [comment]
Looks like this is specifically when transcoding.  Since you already tracked down the problem and the fix, feel free to open a PR and get some credit for it.
