### ISSUE TITLE
External Subtitle not working since recently

### ISSUE THREAD

**Issue by Cosmonear** [jellyfin/jellycon#175]
**Describe the bug**
External Subtitle not working since recently

**To Reproduce**
Have an external subtitle, and play a video. You can select the subtitle, but it will not show up in the video.
It worked great 1 month ago.

**System (please complete the following information):**
- OS: Android TV
- Jellyfin Version: 10.8.0
- Kodi Version: 18.9
- Jellycon Version: 0.5.1

**Additional context**
In the new Jellyfin release, they modify the subtitle section : Refactor and extend external subtitle and audio handling #7255
https://github.com/jellyfin/jellyfin/pull/7255

We Already had a similar issue in the past : #68

**Comment by ViewAfterReview** [comment]
I am facing the same problem with kodi 19.4

**Comment by mac1202** [comment]
Same issue for me.

**Comment by mcarlton00** [comment]
In 10.8, the server has stopped accepting language codes when requesting subtitle tracks.  ie: `Stream.srt` will download correctly, but `Stream.eng.srt` will not.  We're trying to identify if this is a new bug or if I was relying on a bug in the old functionality in 10.7.  Unfortunately, if we revert back to just using `Stream.srt`, then it causes all external sub tracks to be displayed in Kodi as `Unknown - External`.

**Comment by Shadowghost** [comment]
Caused by the removal of [this lines](https://github.com/jellyfin/jellyfin/blob/53186c766bddf954483d7b40e385b382eabd0d8e/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L147-L151) in 10.8.

They allowed requesting the subtitle with an arbitrary filenames leading to the server returning the original file unconverted as the requested filename.

**Comment by Cosmonear** [comment]
> In 10.8, the server has stopped accepting language codes when requesting subtitle tracks. ie: `Stream.srt` will download correctly, but `Stream.eng.srt` will not. We're trying to identify if this is a new bug or if I was relying on a bug in the old functionality in 10.7. Unfortunately, if we revert back to just using `Stream.srt`, then it causes all external sub tracks to be displayed in Kodi as `Unknown - External`.

Hello mcarlton00.
What is strange is that the Jellyfin application on Android TV, smartphone and others, correctly displays the language of the various external subtitles.
I guess you use the same API in Jellycon.
So it should be possible to retrieve this information somehow.

**Comment by mcarlton00** [comment]
It's nothing to do with the Jellyfin api, it's just working within the constraints of Kodi.  When you have external subs, you have to give Kodi a URL to where the sub file is located.  Kodi then parses that URL/file and extension and determines the language it should display based on the URL, and I have no way available to override that.  For example:

| File name in URL | Kodi displays |
| ---- | ---- |
| `Stream.srt` | `Unknown - External` |
| `Stream.eng.srt` | `English - External` |
| `Stream.ger.srt` | `German -> External` |

So it's looking like I'm going to have to write a translation layer so I can pass Kodi a URL that has a language code in it, but then intercept it when Kodi requests the file from the server and change it to not have a language code in the actual api request.  It's not going to be overly difficult, just unexpected and a few hoops to jump through
