### ISSUE TITLE
Plugin fails to load libraries window

### ISSUE THREAD

**Issue by cmsimike** [jellyfin/jellycon#192]
**Describe the bug**
Switching users causes selecting "Jellyfin Libraries" to fail

**To Reproduce**

1. Login as user "a"
2. View that user's libraries
3. Login as user "b"
4. See that user's libraries
5. Switch back to user "a"
6. See that the user is logged in
7. Select "JellyFun Libraries"
8. Note the error

**Expected behavior**
I should be able to load up my libraries after switching users

**Logs**
```
2022-07-20 21:46:56.078 T:1270100   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.jellycon/?mode=SHOW_ADDON_MENU&type=library
2022-07-20 21:46:56.084 T:1269150   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellycon/?mode=SHOW_ADDON_MENU&type=library) failed
```

**Screenshots**

**System (please complete the following information):**

- OS: Ubuntu 20.04
- Jellyfin Version: 10.8.1 
- Kodi Version: 19.4
- Addon Version: .5.4

**Additional context**

**Comment by mcarlton00** [comment]
This appears to have something to do with how the server links a device to a user.  After swapping to a cached user the api requests are giving a 401 response and indicating it's an invalid token, even though it was just being used without error.
