### ISSUE TITLE
View change is not applied to other lists of same type

### ISSUE THREAD

**Issue by bwachtendorf** [jellyfin/jellycon#201]
**Describe the bug**
When changing the view for a season or episode list, the settings are only saved for that specific show or season.

**To Reproduce**
1. Go to a TV show season
2. Change view from default to something else
3. Go to different season

**Expected behavior**
The view change should also be applied to the season where the view hasn't been changed.
This is the behavior for native libraries.

**System (please complete the following information):**
 - OS: Android
 - Jellyfin Version: 10.8.1
 - Kodi Version: 19.3
 - Addon Version: 0.5.5

**Additional context**
This problem occurs on the default skin aswell as Arctic: Zephyr - Reloaded.

**Comment by mcarlton00** [comment]
When you've changed the view on something, highlight anything in that folder (for example, if you've changed the view of a season, highlight an episode) and open the context menu.  Select the option "Set as default view".  It then remembers that and reuses it for that item type.

**Comment by bwachtendorf** [comment]
Yeah that works.
Couldn't find that option after searching for an hour and scouring the web.
Thank you for your help!
