### ISSUE TITLE
cant detect local server, change user

### ISSUE THREAD

**Issue by reitenth** [jellyfin/jellycon#233]
updated to jellycon 0.6 and started happening on only one of my shields. here are the logs
https://paste.kodi.tv/asibexasox

**Comment by mcarlton00** [comment]
That's an odd place to be suddenly failing.  The code surrounding that hasn't changed in ~7 months, so it should have been erroring through the last few releases as well.  It's worth noting that line only gets hit when you don't have PIL installed, which may explain why some devices are working and others aren't if they aren't totally in sync package wise.  But it's definitely something that should get fixed

**Comment by reitenth** [comment]
So what is the issue? I have done nothing to kodi. I dont know how to check pil.

**Comment by reitenth** [comment]
Reinstalled kodi and everything is working
