### ISSUE TITLE
"Recently added" for movies is not limited to the defined number of items

### ISSUE THREAD

**Issue by IncredibleLaser** [jellyfin/jellycon#243]
**Describe the bug**
When opening the "Recently Added" entry for a movie type library, Jellycon lists all items in the library, sorted by added date, instead of only the defined number of items. I guess the issue is with resources/lib/menu_functions.py starting in the block in line 1023, missing  the appropriate line for setting the limit (params["Limit"] = item_limit). It is only honored in the entry label.

**To Reproduce**
1. Go to any library of type movie that has more entries than you have defined as your limit.
2. Click on "Recently Added (your defined limit)"
3. The list contains more items than your defined limit, despite the entry label claiming the opposite.

**Expected behavior**
The list should only include the number of items you have previously defined.

**System (please complete the following information):**
 - OS: Android (Issue exists on both Android TV and FireTV)
 - Jellyfin Version: 10.8.4
 - Kodi Version: 19.4 and 20 Alpha 3
 - Addon Version: 0.6.1+py3

**Comment by mcarlton00** [comment]
Looks like you've already narrowed it down.  I must have missed that block when I went through these a few months ago.  Since you've already put in the work to find it, feel free to open a PR and get some credit.
