### ISSUE TITLE
force h265 will be ignored

### ISSUE THREAD

**Issue by Gee1111** [jellyfin/jellycon#247]
**Describe the bug**
force h265 will be ignored, JF serer always uses h264

**To Reproduce**

- got to jellycon settings in kodi Matrix and activate force 265

**Expected behavior**
when h265 is forced, it should be used

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: every os
 - Jellyfin Version: latest
 - Kodi Version: 19.4
 - Addon Version: latest

**Additional context**

**Comment by mcarlton00** [comment]
I'm pretty sure that setting is the exact opposite of what you think it is.  `Force transcode h265 (hevc)` doesn't mean transcode _to_ h265.  It means if any videos currently are encoded as h265, they will be transcoded to be more compatible with the client.  As an example, I have a Pi 3 that can't play h265 smoothly, but toggling that setting allows it to transcode on the server and play with no problems.

**Comment by Gee1111** [comment]
oooohhhh ok thx i will test

**Comment by mcarlton00** [comment]
If that setting is disabled and it's still trying to transcode, something else is triggering it.  Either a codec issue of some kind, exceeding bitrate limits, etc.  The server dashboard might say why.  The addon will never request a transcode _to_ h265 currently.
