### ISSUE TITLE
Unable to conduct install

### ISSUE THREAD

**Issue by Pixie35** [jellyfin/jellycon#248]
**Describe the bug**

Unable to install JellyCon on LibreELEC device. Following these instructions: https://jellyfin.org/docs/general/clients/kodi/#add-on-repository on a fresh install of LibreELEC & Kodi. Jellyfin repo successfully added as per docs. Conducting this step "Select the JellyCon add-on and choose install", when I get the following error: "The dependency on script.module.requests version 2.22.0+matrix.1 could not be satisfied."

Digging into it further I went to the kodi repo and downloaded the dependency, transfered via usb to the device and attempted to install that. This then prompted a different error "The dependency on xbmc.python version 2.25.0 could not be satisfied." 

It seems that there is a python mismatch in the dependencies.

**To Reproduce**

1. Add Jellyfin Repo as per Jellyfin docs.
2. Attempt to add JellyCon as per Jellyfin docs.
3. See error.

**Expected behavior**

Successful Jellyfin install!

**Logs**

Unable to get a paste of logs off device.

**Screenshots**

**System (please complete the following information):**
 - OS: LibreELEC 10.0.2
 - Jellyfin Version: 10.8.4
 - Kodi Version: 19.4
 - Addon Version: 0.6.1+py3
- Hardware: RPi 400

**Additional context**

I also can't seem to reach the Offical Kodi Repo on the device, but both the LibreELEC and Jellyfin ones connect just fine?

**Comment by mcarlton00** [comment]
Kodi 18/19 have breaking changes between them and require different dependency versions.  When you tried to install Jellycon and it gave a version number of `2.22.0+matrix.1`, this indicates that you were trying to install the Kodi 19 version (which is correct).  However, it looks like you then tried to install the requests library released for Kodi 18, which has a different python version and isn't compatible.

Ultimately, this is an upstream Kodi mirror problem.  For some reason, sometimes they just seemingly implode and refuse to serve packages that are requested.  The most common way I've found to get around this is to either wait for 12/24 hours so your cache expires and you get a different mirror, or to delete the `~/.kodi` directory on your device and try installing again from scratch.  There's really not much we can do about it, unfortunately.

**Comment by Pixie35** [comment]
I intend then, to link this into the offical kodi github, since being unable to request the right packages from their mirrors is the actual issue here.
