### ISSUE TITLE
Playback reboots Kodi

### ISSUE THREAD

**Issue by kmevse** [jellyfin/jellycon#251]
When I skip forward in movie or the movie has been watched on different device to certain point in time, the RPi 4 with LibreELEC reboots the KODI (not the whole device). When the playback starts from he beginning, the movie plays fine. 

```
Dec 20 20:47:24 LibreELEC kernel: rpivid feb10000.codec: rpivid_h265_start: (3840x1600)
Dec 20 20:47:24 LibreELEC kernel: rpivid feb10000.codec: SPS changed
Dec 20 20:47:24 LibreELEC kernel: rpivid feb10000.codec: PPS changed
Dec 20 20:47:25 LibreELEC kernel: rpivid feb10000.codec: PPS changed
Dec 20 20:47:27 LibreELEC kernel: rpivid feb10000.codec: rpivid_h265_stop
Dec 20 20:47:53 LibreELEC kodi.sh[1086]: Segmentation fault (core dumped)
Dec 20 20:47:57 LibreELEC kodi.sh[1086]: Crash report available at /storage/.kod/temp/kodi_crashlog_20221220204753.log
Dec 20 20:47:57 LibreELEC systemd[1]: kodi.service: Main process exited, code=exited, status=139/n/a
Dec 20 20:47:57 LibreELEC systemd[1]: kodi.service: Failed with result 'exit-code'.
Dec 20 20:47:59 LibreELEC systemd[1]: kodi.service: Scheduled restart job, restart counter is at 2.
Dec 20 20:47:59 LibreELEC systemd[1]: Stopped Kodi Media Center.
Dec 20 20:47:59 LibreELEC systemd[1]: Starting Kodi Media Center...
Dec 20 20:47:59 LibreELEC systemd[1]: Started Kodi Media Center.
```

[kodi_crashlog_20221220204753.log](https://github.com/jellyfin/jellycon/files/10271974/kodi_crashlog_20221220204753.log)

**Comment by mcarlton00** [comment]
There's likely nothing we're going to be able to do about this here.  We simply hand Kodi a URL and tell it to play.  All the actual playback code is within Kodi proper.  Especially since it's a seg fault and it's breaking in the C code instead of a python error.  I'm not sure I could cause that to happen even if I tried.

Does this happen in any other addons?  fwiw, I've never seen this happen in libreelec on a Pi 3

**Comment by kmevse** [comment]
It never happened with other add-ons or with playback from SMB. Do you suggest I raise this issue with Kodi or LibreELEC?

**Comment by mcarlton00** [comment]
It's hard to say.  I hate to just say "it's somebody else's problem" with no guidance, but I don't know C, so I personally can't make heads or tails of the stacktrace.  Somebody from one of the other projects may be more help understanding why the crash is occuring.  

Can you try updating to LibreElec 10.0.3?  I'm not sure if it would have any effect or not, but it's possible it was a bug that has been fixed upstream.

https://libreelec.tv/2022/10/17/libreelec-matrix-10-0-3/

**Comment by kmevse** [comment]
I think it is not the issue of Jellycon as you say. I updated to 10.0.3 and I got black screen, had to change PRIME Render Method to Direct to Plane but now I do not have audio pass-through for some reason. I guess I will ask LibreELEC guys about that. But positive outcome is that the restart of Kodi is gone, maybe it was an issue of EGL. Thank you for help.
