### ISSUE TITLE
No TV Shows shown with 0.7/Jellyfin 10.8.9

### ISSUE THREAD

**Issue by gbeine** [jellyfin/jellycon#279]
**Describe the bug**

When using the version 0.7 of the plugin together with Jellyfin 10.8.9 no TV Shows appear in the library.
Only the unwatched series appear in the according "folder", all other folders, e.g. the all shows folder, are empty.
The plugin reports the correct number of series while fetching the items, so it seems to be a problem of displaying the shows.

(It works with movies and music as expected, the issue is only with TV shows.)

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: OSMC
 - Jellyfin Version: 10.8.9
 - Kodi Version: 19.5
 - Addon Version: 0.7.0

**Additional context**

**Comment by mcarlton00** [comment]
This sounds like either you've manually tweaked views in Kodi itself or there's a quirk in whatever skin you're using.  This addon has no frontend and has no influence on how things are displayed.  And as I use this everyday, I feel fairly confident in saying the addon is functioning as intended and not broken in such a critical way.
