### ISSUE TITLE
Fix TMDb integration

### ISSUE THREAD

**Issue by ltguillaume** [jellyfin/jellycon#285]
This is just a question.

I just set up a new Kodi environment and found that often the metadata I'm used to in Jellycon (e.g. actors per episode) weren't showing up. Instead I just see a banner.

I'm wondering why this is happening. Is the metadata gathered by the server or locally?

Installed: The Movie Database Python (default for Kodi) 2.1.0
Not installed: The Movie Database 3.5.14

**Comment by SethFalco** [comment]
> Is the metadata gathered by the server or locally?

Metadata is gathered by the server, and the device running Kodi will request it from the Jellyfin server.

> (e.g. actors per episode) weren't showing up. Instead I just see a banner.

Could you elaborate on "I just see a banner"? It probably depends on the skin you're using, so I just want to get an idea of what you're seeing.

On a per movie/series basis, it is possible to get cast members already, though it's disabled by default.

![](https://github.com/jellyfin/jellycon/assets/22801583/7da52200-40b5-4b03-b4bf-11ab934d112d)

**Interface** → **Item Details** → **Include people** (Enable)

![](https://github.com/jellyfin/jellycon/assets/22801583/554317d2-96e0-4b9a-a3dc-7a68a60a69d8)

Are you expecting to see this same information, but on a per-episode basis? If so, can you please share which skin you're using? Then I can review this further?

**Comment by ltguillaume** [comment]
Nope, I meant this info for a show. Most shows work by now, though, so it might have been server-side. What I still see for some shows right now is a banner like this:

![image](https://github.com/jellyfin/jellycon/assets/4777345/b39dfb3e-4948-453f-86be-c38d968d498b)

or "Cast not available", like on your screenshot:

![image](https://github.com/jellyfin/jellycon/assets/4777345/2cce8260-9502-465f-8efa-4c721bb884e8)

and when I press Up a few times to get there, I see:

![image](https://github.com/jellyfin/jellycon/assets/4777345/7420e842-0eaa-44e7-80bd-8205239e4583)

**Comment by mcarlton00** [comment]
The actor info comes from the server, we don't do any metadata retrieval locally ourselves.  So it's dependent on what the server provides and if you have the flag turned on in the settings (I'm assuming you do).  I don't believe the server provides cast members for episodes, only shows and seasons.

If the server doesn't report any cast members, it tries to display a banner.  I'm guessing if the show in question doesn't have a banner associated to it in the server that's when it falls back to the "Cast not available" message, but I haven't done any in depth digging into that behavior
