### ISSUE TITLE
Dependency error installing Kodi addon on Kodi Nexus 20.1

### ISSUE THREAD

**Issue by whisperdancer** [jellyfin/jellycon#291]
**Describe the bug**
Kodi nexus 20.1 unable to install jellyfin addon. Receive dependency error upon install.

**To Reproduce**

1. Add source https://kodi.jellyfin.org. This works fine.
2. Install from Zip File, Install repository.jellyfin.kodi.zip. Works fine. 
3. From within Kodi, navigate to "Add-on Browser"
4. Select "Install from Repository"
5. Choose "Kodi Jellyfin Add-ons", followed by "Video Add-ons"
6. Select the Jellyfin add-on and choose install
7. See Error: 2023-07-04 10:25:39.459 T:954     error <general>: CAddonInstallJob[plugin.video.jellyfin]: The dependency on script.module.requests version 2.22.0+matrix.1 could not be satisfied.

**Expected behavior**
I expect the addon to install and prompt for connection details

**Logs**
2023-07-04 10:24:25.585 T:933      info <general>: CAddonMgr::FindAddon: repository.jellyfin.kodi v1.0.0 installed
2023-07-04 10:25:39.459 T:954     error <general>: CAddonInstallJob[plugin.video.jellyfin]: The dependency on script.module.requests version 2.22.0+matrix.1 could not be satisfied.

**System (please complete the following information):**
 - OS: Jellyfin server on Pi4 RaspPI 64bit OS
 - Client throwing the error is on another Pi4 running Kodi LibreElec 20.1 Nexus
 - Jellyfin Version: 10.8.10
 - Addon Version: 0.7.10+py3

**Comment by whisperdancer** [comment]
Update. I deleted the ~/.kodi folder, rebooted system and tried install again. I have no idea why, but it installeds this time. However, after connecting to the server it fails to sync. The log is throwing a ton of errors. It appears the jellyfin addon is not compatible with kodi 11 nexus at this time. I do hope an updated version gets released that will be compatible and work with kodi 11 nexus as it has many improvements over kodi 10.

**Comment by SethFalco** [comment]
Hmm, could you elaborate on what "Kodi 11 Nexus" refers to?

There is Kodi 11, which is Eden. And there's Kodi 20 which is Nexus.
Either I'm misunderstanding something, or you've mixed up Kodi 11 and Kodi 20.

I personally use Kodi 20 Nexus, and JellyCon works flawlessly.

**Comment by whisperdancer** [comment]
I'm using LibreELEC 11.0.3 has been released, bringing Kodi (Nexus). So it's Kodi 20 Nexus and that's the one I'm having all the dependency issues with. Curious how did you install Kodi? Are you using Libre or another distribution?

**Comment by SethFalco** [comment]
Later, when I have time, I'll grab my spare RockPro64 and try to install JellyCon on a fresh installation of LibreELEC 11.0.3 to see if I can reproduce the issue. 

For now, I'm using the following and had a flawless experience:

## LibreELEC

Distro: LibreELEC 11.0.1  

## Kodi

Build: 20.1 (20.1.0)  
Git: 20.1-Nexus  
Compiled: 2023-03-18  
Arch: RK3399.arm

**Comment by whisperdancer** [comment]
Issue resolved.
