### ISSUE TITLE
Add "Force transcode AV1" option

### ISSUE THREAD

**Issue by njanke96** [jellyfin/jellycon#301]
I noticed there's options in the add-on settings to force transcoding for H.265 content, etc. I have a device that can't hardware decode AV1. AV1 media plays but it isn't smooth since the device lacks the power required to software decode. I can long-press the title I want and choose "Force transcode", and the server transcodes to h264, which plays smooth and looks good enough on high bitrates, but it isn't ideal having to do this every time.

I'm wondering if it would be possible to add a similar option to force transcode all AV1 content.

Thanks for the work on this add-on, it's very smooth!

**Comment by mcarlton00** [comment]
I haven't had a ton of time to devote to this lately (or any AVI files to test with myself), but this should be pretty straightforward if you wanna take a crack at it yourself.  It should basically just be adding to the `settings.xml` and adding another if statement to this function.  https://github.com/jellyfin/jellycon/blob/88f3437a5fdcb20220709526b5d9e2f7c9ec7d73/resources/lib/play_utils.py#L1509-L1517

**Comment by njanke96** [comment]
I implemented it as you described and it seems to be working. I built the addon zip as done in the build action and tested on my desktop. The server transcodes AV1 to h264 as expected.

https://github.com/jellyfin/jellycon/pull/303
