### ISSUE TITLE
New Jellyfin 10.9 sends "CollectionType" as capital string

### ISSUE THREAD

**Issue by DaRealHansForSure** [jellyfin/jellycon#302]
**Describe the bug**
In a newer Jellyfin Server version (10.9 at level commit `906f701fa81c7cde1a9a01b066f3f29ff98552a5`) the `CollectionType` is new an enum and get translated to the capital version of the string, `Jellycon` can't handle that, because its `case-sensitive`

**To Reproduce**

1. Start a Jellyfin 10.9 server at level commit `906f701fa81c7cde1a9a01b066f3f29ff98552a5`
2. Create a Library with movies in it
3. Link Jellycon to it
4. Often the Folder does not show up in Jellyfin

**Expected behavior**

Seeing the Folder, but doesn't work

**Screenshots**

![image](https://github.com/jellyfin/jellycon/assets/3436574/11986df4-a7be-4051-b80a-b60244c3eccf)

**System (please complete the following information):**
 - OS: Windows 10 (but doesn't matter)
 - Jellyfin Version: 10.9
 - Kodi Version: 20.2
 - Addon Version: v0.7.0+py3

**Additional context**

As i debugged the code and was looking through, the fix is simple.
Everywhere the `CollectionType` property gonna be accessed from the `API`, you should `lower` the result for your checkt.

Demonstrate the example in `lib/menu_functions.py` -> `set_library_window_values`
***Before***
```python3
collection_type = item.get("CollectionType", "mixed")
if collection_type in ["movies", "boxsets", "music", "tvshows", "mixed"]:
```

***Fix***
```python3
collection_type = item.get("CollectionType", "mixed").lower()
if collection_type in ["movies", "boxsets", "music", "tvshows", "mixed"]:
```

**Disclaimer**
This is my first issue report since programming, hope it is okey...

**Comment by mcarlton00** [comment]
Good catch, thanks for the report (and example fix).  We're discussing this internally and it probably likely have more far reaching impacts than just this client, so it's most likely going to be changed in the server to be lowercase again.  If it does stay as it currently is we can get you to make a pull request so you get credit for the fix.

**Comment by DaRealHansForSure** [comment]
Thank you for your feedback. Thats true, Jellyfin Server should make some changes here. 
I think the Error happened general in https://github.com/jellyfin/jellyfin/pull/9764 , but it seems also  to have an bug in `saving the collection type to database`

Newly created folders don't have `CollectionType` in `API output`

I think you don't need to do something, but in general, my advice would be: always compare to `case-insensitive` when not needed

Have a good day :)

**Comment by thornbill** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/10702
