### ISSUE TITLE
Extreme stuttering making all videos unwatchable

### ISSUE THREAD

**Issue by PureTryOut** [jellyfin/jellycon#330]
**Describe the bug**
Any video I play using Jellycon has an extreme stuttering problem. This while the same video plays fine using the Jellyfin web interface on my PC, even if the server has to transcode for it.

The machine (a RockPro64) has native support for HEVC/x265 files but even if playing those directly (without transcoding) the stuttering makes it unwatchable.

**To Reproduce**
1. Start any video from Jellyfin

**Expected behavior**
The video to play smoothly.

**Logs**
Not sure where to get these from.

**System (please complete the following information):**
 - OS: LibreElec 11.0.6
 - Jellyfin Version: 10.8.10
 - Kodi Version: 18.3
 - Addon Version: 0.8.0

**Additional context**
This is running on a RockPro64 which is officially supported by LibreElec. The connection to the Jellyfin instance is using a direct IP, so everything stays within the network. The connection is a 100MBit line.

Because of this issue I basically can not watch Jellyfin on my Kodi instance.

**Comment by mcarlton00** [comment]
Are you sure you've configured hardware decoding in Kodi?  JellyCon has no impact on playback at all, we just hand Kodi a URL and it handles all the playback on it's own.  You'll likely have the same results just trying to play the files locally without going through a Jellyfin server.  This sounds like your hardware either can't play the video, or Kodi isn't aware how to reach the hardware acceleration bits.

**Comment by PureTryOut** [comment]
I mean, this is an official image from LibreElec made specifically for this device, I'd assume hardware decoding is configured correctly by default. I'm new to Kodi, I don't know how I would configure it otherwise.

I'll try to play a file directly tonight but I'd be amazed if that doesn't play smoothly either.

**Comment by mcarlton00** [comment]
It sounds like either your install doesn't have codec support enabled, the device isn't actually capable of playing HEVC directly, or you have network issues and it can't keep up.  The last one seems the least likely, imo.

To look into hardware acceleration (assuming libreelec hasn't moved it, or has another config location), go to Settings -> Player.  Switch the settings mode from Basic to Advanced or Expert.  This will give you _way_ more options under the Videos section.  I don't have any good guidance on tuning this, unfortunately, so I won't be much help there.

**Comment by PureTryOut** [comment]
Well I finally got the chance to plug in a USB-stick to play the files directly on-device, those play just fine. So hardware acceleration doesn't seem to be the problem.

**Comment by PureTryOut** [comment]
So... It seems either the hardware or something in LibreELEC is having _extreme_ issues with Wi-Fi. Besides constantly asking for the password, downloads in general are extreme slow (it took half an hour to download a system update...).
I plugged in an ethernet cable and all issues magically disappeared.

So, hardware/LibreELEC problem. Nothing to do with Jellycon... Derp, sorry bothering you.
