### ISSUE TITLE
jellycon doesn't action EDL files (for skipping intros or ads)

### ISSUE THREAD

**Issue by cooljimy84** [jellyfin/jellycon#341]
**Describe the bug**
Intro skipper makeS EDL files that kodi will skip on normal playback, but playback through jellycon doesn't skip the intro.

**To Reproduce**
Create EDL file with time code (or just install intro skipper https://github.com/jumoog/intro-skipper)
Playback through kodi to test where the jump point is.
Playback through jellycon 

**Expected behavior**
Jump at the time code in the EDL file

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: MintOS (ubuntu)
 - Jellyfin Version: 10.9.6
 - Kodi Version: 20.2.0
 - Addon Version: 0.8.0 py3

**Additional context**

**Comment by mcarlton00** [comment]
Yeah, this isn't going to happen, sorry.  We hand Kodi a single URL of where to find the stream and that's the end of our involvement in the playback process.  I'm not sure if/how it's even possible for us to retrieve those EDL files, but it really doesn't matter.  In the past, the intro skipper plugins would automatically send skip commands out to clients over a websocket connection.  If they've removed that ability, it's not going to work anymore.  Official clients don't support third party plugins, as there's too much variance and likelihood of breakage.

**Comment by cooljimy84** [comment]
I kinda thought that if it wasn't already there it might be a tech reason, rather than just an ignore/bug. I think there is another project that adds chapter markers rather than EDL files.
Thanks for the Awesome work on this project ppl.
