### ISSUE TITLE
Playlists no longer appear in jellycon, under libraries or Music.

### ISSUE THREAD

**Issue by surfrock66** [jellyfin/jellycon#342]
**Describe the bug**
Jellycon currently provides no way I can find to play playlists.  In the UI, other posts say playlists should appear under "Libraries" in Jellycon, but they don't for me, see here: https://github.com/jellyfin/jellycon/issues/128#issuecomment-1179781966

**To Reproduce**
1. Go to "Addons" and select "Jellyfin Libraries"
2. Playlists is not in this list
3. Go to "Music"
4. None of the list items are playlists.

**Expected behavior**
Playlists available in the Jellyfin android app or web UI should be visible

**Screenshots**
![image](https://github.com/user-attachments/assets/429a1cad-f43c-450b-a114-b3995e215674)
![image](https://github.com/user-attachments/assets/c061f96e-c6dc-41c5-a87c-4a6b4b45ab70)
![image](https://github.com/user-attachments/assets/ae33d0e7-a6f0-48ed-8a26-763d39fd681c)

**System (please complete the following information):**
 - OS: LibreElec 11.95.2
 - Jellyfin Version: 10.9.7
 - Kodi Version: 21.0.0
 - Addon Version: 0.8.0+py3

**Additional context**
The playlists are visible in the web UI.

**Comment by mcarlton00** [comment]
![Image](https://github.com/user-attachments/assets/1ccc9f57-a610-49ea-afd5-1561e7ab81e3)

Can't replicate.  Tested on multiple devices and playlists show up in my list of libraries just fine.  Adding them into a music library view hasn't happened yet because of the required filtering (which will likely be slow), they'll only show up in the list of libraries currently.

**Comment by surfrock66** [comment]
Can you expand how you get it to show up?  If you're in your Jellyfin web interface, I go to "Music" which is my main music library, and there's a tab at the top for "Playlists" and in there I can see 2 kinds of playlists; those created in the Jellyfin UI, and .m3u8 files imported when the library is scanned.  When I load kodi, go to programs, go to JellyCon, go to "Jellyfin Libraries" it's not there, and if I go to the "Music" library there's no playlists there either.  I have experimented with adding all kinds of custom shortcuts to the main menu and I never get a "Playlists" entry.

**Comment by mcarlton00** [comment]
Nothing.  That menu is populated directly from the Views api endpoint in the server, which is the same endpoint that the web UI uses on the home screen.  If you don't have playlists showing up there, it means your user doesn't have the playlists view.  Possibly you disabled it in your settings.  But there's nothing to _do_ client side, it simply displays what the server provides.

**Comment by surfrock66** [comment]
That was it; the account we use for our kodi boxes had that unticked, I don't even know how that happened, no one logs into that account.  Thank you!
