### ISSUE TITLE
Jellycon not updating library

### ISSUE THREAD

**Issue by BoKKeR** [jellyfin/jellycon#347]
**Describe the bug**
Calling update from movies/series results in 1 second scan. No new items are ever added. Tried reinstalling and re-authenticating jellycon. Cleaning database.

**Expected behavior**
I would expect both upon startup and upon library update local and remote to get the library updated

**Logs**
[kodi.log](https://github.com/user-attachments/files/17061346/kodi.log)

**System (please complete the following information):**
 - OS: Libreelec
 - Jellyfin Version: 10.9.10
 - Kodi Version: 21.1
 - Addon Version: 0.8.0+py3

**Additional context**
I have had this problem for while. I can find the new content by going into files and manually starting it from there. The plugin also fails to find my local instance running on 8096 so I am connecting using the remote address

**Comment by hagaygo** [comment]
Not sure which option you use by "Calling update" from jellycon addon.

But on my use case , i set jellyfin server to update library every X minutes.
On jellycon i have no need to "update/refresh" , just going back and forth to same library returns up to date data.

(Make sure you are not mistaking jellycon addon for jellyfin addon which works differently)

**Comment by BoKKeR** [comment]
Closing this issue, accidentally used jellycon instead of jellyfin for kodi!
