### ISSUE TITLE
What does the option "Direct file playback" do?

### ISSUE THREAD

**Issue by kroese** [jellyfin/jellycon#353]
What does the option "Direct file playback" do? It sounds very useful, but I cannot find any information about its purpose, so its hard to decide if I should enable or disable it.

**Comment by mcarlton00** [comment]
Nothing.  It was originally meant as a way to bypass the server and play media files directly from the source, but this is not a supported configuration and is no longer possible in the server.  It just hasn't been removed from the settings yet.
