### ISSUE TITLE
Prevent connection error pop-up

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellycon#41]
The connection error pop-up keeps constantly popping up and doesnt leave the screen.

**Comment by ltGuillaume** [comment]
Same here, it's impossible to use Kodi if this add-on has any connection error.

**Comment by mcarlton00** [comment]
Is it constantly coming back immediately, or is there a delay between attempts?  Wondering if this is bad loop logic on startup or something like trying to populate the backgrounds that cycle periodically.

**Comment by ltGuillaume** [comment]
I've seen many overlap, but it's difficult to reproduce. If I just cut the connection, I only see one at start-up. I'll report back if I see it happening again.

**Comment by RicardoCst** [comment]
Its not that its looping indefinitely, its that the erroe messages are so long that they take forever to disappear

**Comment by mcarlton00** [comment]
I'm still unable to replicate this.  I'm gonna close this and if anybody sees it happen again please open a new issue

**Comment by ltGuillaume** [comment]
Haven't seen it anymore, but I do have "Suppress notifications for connection errors" enabled.
