### ISSUE TITLE
How can I integrate Jellycon into another skin than the base Estuary ? (or make it more configurable)

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellycon#43]
Hi,
I was using the Jellyfin for Kodi addon for a long time. It had the advantage of adding everything to the Kodi library, making it usable with any skin easily and the library was shared to Android remotes. But the issue is the refresh that sometime causes problems, takes time, etc....

Jellycon however, doesn't have to sync and that's a huge improvement. But the downside is the integration to the main menu. It works great in the addon itself, but having everything on the front page is better. I found the setting to clone the base Estuary and add Jellycon function to it, but I don't like this skin. I don't like the left panel that hides itself for example, nor the player.

Is there a way to add Jellycon functions to another skin ?

I tried adding Jellycon shortcuts to Estuary Mod, my favorite skin that allows full configuration of the main menu. But it was very unstable.
Finding a way to add Jellycon to the main menu would finally meet the advantages of jellyfin for kodi and Jellycon. Because so far I am always making compomises between both.
Thanks in advance for any answer

**Comment by mcarlton00** [comment]
I'll admit that I'm not a huge fan of the current clone skin implementation, but that's a can of worms to work through I haven't had time to deal with yet.  I can only assume that removing the side bar was a purposefully done design choice, though it seems disingenuous to "clone" something and then fundamentally change how it looks/behaves in that drastic of a way.

Every skin is unique, so I can't really give real in depth instructions, though you may want to take a look at #14 for an idea of how to populate your skin.
