### ISSUE TITLE
Resume or play from beginning not working unless willing to be asked twice

### ISSUE THREAD

**Issue by MrPedroG** [jellyfin/jellycon#48]
This is what is happening (I am using the latest jellycon version available with the latest stable Jellyfin server available and Kodi 18.9 - I am using direct play):

With context menu option ON in jellycon configuration: 

      (Only) when I click play (enter) on a half-watched item, I get the special context menu in a kind of greyish box (style not matching the skin) with many options (transcode, mark as, delete, etc.) but none of them is to resume from were I left it. If I click on an item that has not been watched at all, it just plays.

With context menu OFF: 

      If I configure auto resume OFF, when I click play (enter) on a half-watched item, then I get 2 popups:
          First a popup from Kodi (matching the style of the skin) with both options, play from beginning or resume from ...
          Then another from the addon (again, greyish box style, nothing like the Kodi's skin) with exactly same options
          (BUT: the response that matters is what you select on the second popup - what I select on the first one is ignored).
 
     And, if I configure auto resume ON, then, when I click play (enter) on a half-watched item, I only get the Kodi popup, but it does not matter what I select, it always resumes.

IMPORTANT: Every time I change the configuration of the jellycon regarding context menus and/or auto-resume, it seems that you need to close Kodi and open it again, or it does weird things. Restarting Kodi, however, produces consistent results as described above.

ALSO: My current Kodi settings for System/Settings > Videos > File list > Default action >     is PLAY

Thank you in advance for looking at this. Please let me know if I can be of assistance.

PS. I was using Plex / PlexKodiConnect until recently. I am giving Jellyfin a try. I started with Jellyfin for Kodi but had issues with changes on the media library not showing on Kodi. Jellycon avoids, logically, any synching issues. It is slightly slower but we are talking 2-3 longer seconds to load the views.

**Comment by MrPedroG** [comment]
Found way around it: 
Disable context menu in jellycon
Disable auto resume in jellycon
And, on Kodi System/Settings > Videos > File list > Default action > Put RESUME

This way, when clicking on a half watched item, Kodi does not show its dialogue box but only jellycon does, and it reacts correctly.

**Comment by mcarlton00** [comment]
I'm not able to replicate this.

Default action - Play
Auto resume on - It resumes from the previous location
Auto resume off - I get a single prompt (black and grey) asking if I would like to resume or start from the beginning

![2021-03-01-194624_596x258_scrot](https://user-images.githubusercontent.com/17029228/109579410-d6282300-7ac6-11eb-930c-e219748471f0.png)

What I choose on this box is what happens.  I'm not sure where the second resume prompt you're getting could be coming from.  Logs may be helpful in determining that. https://kodi.wiki/view/Log_file/Easy

**Comment by MrPedroG** [comment]
I think you can close this. Whether you get one or two prompts depends on what you have in:
 Kodi System/Settings > Videos > File list > Default action > 

By setting it to RESUME you just get one prompt.

Thanks!
