### ISSUE TITLE
Kodi screensaver won't kick in while displaying jellycon view

### ISSUE THREAD

**Issue by MrPedroG** [jellyfin/jellycon#49]
While watching video through jellycon, pressing X will stop video and go back to items view.
Unless you press back or esc to go to Kodi main menu, screensaver will not initiate no matter how long one waits.

Thanks for your help

**Comment by mcarlton00** [comment]
I'm not able to replicate this.  I've tried a few variations and the screensaver always works (as long as it's enabled, of course).  Possibly one of the other fixes I've done since this was opened addressed it.
