### ISSUE TITLE
Continue playback over/undershoots by up to 30 minutes

### ISSUE THREAD

**Issue by ltGuillaume** [jellyfin/jellycon#69]
**Describe the bug**

Using the lates Jellycon on Kodi 18, the playback starts well beyond what I saw last, sometimes even 20-30 minutes further. Sometimes it doesn't save the play position at all. AFAIK this behavior has started somewhere in the last few weeks. 

**To Reproduce**

1. Start playback and stop it manually (I just pressed [x])
2. You may or may not close Kodi
3. Restart playback and it's Russian roulette as to whether your playback resumes at the proper timestamp

**Expected behavior**

Obviously the last playback position should be propagated to the server nicely.

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: version-10.7.2-1 (LinuxServer.io docker image)
 - Kodi Version: 18.9.0
 - Addon Version: 0.4.3+py2

**Comment by mcarlton00** [comment]
Do you mean that it's reporting the time to the server wrong, or that the server is correct but JellyCon plays at the wrong time locally?  I've been trying to do tests and haven't been able to replicate this.

**Comment by ltGuillaume** [comment]
I have no clue, how can I check that, does it report the times reported to the server in the log?

All I know is that the following consistently goes wrong: I press 'x' to stop playback. Kodi then shows, for example, `(69%)` after the item. Then, when I walk downstairs and continue the same file on a different device, it shows `(77%)` next to the item, for example.

**Comment by mcarlton00** [comment]
When this happens, check on the server and see if the time is reported correctly there.  The issue is either in the calculating/reporting to the server, or when calculating time from the server back locally.  If it's wrong in the server as well, that should give me a better idea of where to look.

**Comment by ltGuillaume** [comment]
I just stopped a video at 20:00 mins (which then shows 18% behind it), then I closed Kodi. I reopened Kodi and now I see 25%). I didn't start it, but instead checked the web UI and continued playback there: it started at 28 mins (so ~25%). So I'd say it's in calculating/reporting to the server when stopping playback.

**Comment by mcarlton00** [comment]
I'm not sure what's going on here.  I keep trying to replicate it, but it's been reliably able to pick up in the same place every time.  The only misses were when it moves backwards 1 minute, but certainly no misses going forward like you've seen.  I'm wondering if it's only happening on specific file formats or certain files and none of my test files are triggering it.

**Comment by ltGuillaume** [comment]
For me it's basically _always_ happening. For short episodes of 24 minutes, when I'm past 14 minutes and stop playback, then often when I open Jellycon on a different device I see it's just marked as completed, WTF.

**Comment by Ozymandyaz** [comment]
I am seeing the same thing, and I am seeing it on my x86 install now as well. Its not predictable, as it does not happen every time, but it is somewhat common (10-30% of the time...) The symptom is that a stopped video, that has been stopped for a more then a few minutes, will result in a resume point that is roughly 5-10% (like 2-5 minutes on a 30 min episode) from where it should be. I have not had a chance to do a good clean check of the logs as I see the issue, but anecdotally this is the scenario:

- Stop a show in progress (after 3 minutes, but not more then 80% complete.) 
- Kodi will show the correct progress percentage in the front end, and when the widgets update on the home screen the progress looks correct. (An immediate resume does not appear to have an issue)
- Walk away for some time (generally more then 10 minutes)
- Home page widgets will have updated and progress bar is a little farther ahead on the thumb preview of the affected show
- Start episode, plays form a point a bit farther in the episode.


What it feels like to me is that the "Stopping" action is not being recognized on the server. In fact, if you look at the dashboard of the server after stopping a video in JellyCon, that dashboard continues to increment time and it looks like the video is still playing. Now this happens for any video regardless of the progress being captured correctly or not in Kodi, so it may be a red herring. I did however observe one time that when the dashboard did eventually "stop", the progress was wrong everywhere (Jellyfin web and Kodi) and the resume point was exactly at the same point that the Dashboard said it was at. 

I could not parse out exactly how JellyCon stops video (I am NOT a developer... But I have watched a YouTube video on Python... So hey...) but it almost seems like it just stops requesting as opposed to actually reporting back to the server that that a stream has ended. So perhaps its a socket issue or something where the server is just unaware that playback has stopped for some time.

I believe that this has been happening for a long time, but in my case it was very infrequent until a month or two ago. I cannot back that up with anything concrete.

**Comment by ltGuillaume** [comment]
@Ozymandyaz Really good analysis. I see the same thing. After those few minutes, it doesn't matter if you pick another client (e.g. Jellyfin Android app or web client), they all have their progress set too far ahead. So it's not the receiving end, it's definitely a problem with a (delayed or just wrong?) notification to the server that the video had been stopped.

**Comment by Ozymandyaz** [comment]
Yeah, I actually spent a few minutes this weekend to look at this farther and found that:

If I use the Web client or Infuse (on my iPhone), when I stop playback Jellyfin will log the playback stopped action. 
But if I use JellyCon, the only thing that happens in the Jellyfin Debug log is an update to the KodiSyncQueue.

**Comment by ltGuillaume** [comment]
So it doesn't send a "playback stopped" action at all? Hmz that's odd, then why is the resume position correct sometimes? I don't think Jellyfin server keeps track of how far the video has been _downloaded_  from the server, so there has to be _some_ kind of signal to the server made by JellyCon in order to get a resume position at all.

**Comment by mcarlton00** [comment]
It's definitely doing some progress reporting, but something isn't quite right in it.  I've actually been seeing the opposite issue lately, where I'll watch something all the way through and it gets marked as watched in the server, but then it has partial progress on that file instead of being complete.  It sounds like either network issues (likely websockets), or a race condition where the addon is doing things out of order.  I have a feeling what I've been seeing is probably related to the rest of this.

**Comment by ltGuillaume** [comment]
Yeah, sounds like it. If it's network issues, then it would be that retries of old progress reporting aren't cancelled by new ones, I guess.

**Comment by Ozymandyaz** [comment]
I may be way off here, but I do not think that any of the "OnPlayBackX" events are triggering in JellyCon. I can see the events fire:

```
LibreELEC:~ # tail -f /storage/.kodi/temp/kodi.log | grep -i "onplayback"
2021-10-05 16:54:05.297 T:1006    DEBUG <general>: OnPlayBackStarted: CApplication::OnPlayBackStarted
2021-10-05 16:54:20.932 T:29578   DEBUG <general>: OnPlayBackStopped: CApplication::OnPlayBackStopped
```


But I would have expected to see the Jellycon debug log events also log that it has happened from the class in play_utils.py

```
    def onPlayBackStopped(self):
        # Will be called when user stops kodi playing a file
        log.debug("onPlayBackStopped")
        stop_all_playback(self.played_information)
```

It seems like the script is finishing and then not waiting for the stop event, is there a monitor tha needs to be called to keep the script running during playback?

**Comment by mcarlton00** [comment]
Just an update: I was able to replicate this today.  Was watching a movie, paused it about 20 minutes in to go work in the garage.  When I came back, the screensaver had stopped playback and the resume position was much further than I was when I stopped it.  So I finally have a baseline about where to start.

@Ozymandyaz It's possible I messed up one of the monitor functions when I did updates to be compatible with Kodi 19, I'll need to go review where that happened and see if I caused this accidentally.

**Comment by Ozymandyaz** [comment]
SO I took another long look and I think that he issue is in the Service() class in play_utils... The monitor is working fine and all of the onPlayBack stuff is trapping fine, but...

When this is called:

```
    def onPlayBackStopped(self):
        # Will be called when user stops kodi playing a file
        log.debug("onPlayBackStopped")
        stop_all_playback(self.played_information)
```
self.played_information has no values (i.e. len.played_inforation == 0). I tested this by adding log.debug("played_information **is blank**") in the stop_all_playback function:

```
def stop_all_playback(played_information):
    log.debug("stop_all_playback : {0}".format(played_information))

    if len(played_information) == 0:
        log.debug("played_information is blank")
        return
```
And I saw this in the log:

```
LibreELEC:~ # tail -f /storage/.kodi/temp/kodi.log | grep -i "played_information"
2021-11-03 19:17:27.085 T:122473    INFO <general>: JELLYFIN.resources.lib.play_utils -> DEBUG::resources/lib/play_utils.py:1012 played_information is blank
```

I think in older versions there were some "monitor" arguments being passed around and that all got shifted over to JSON, and I suspect that the class is now looking in the wrong place for the details of the as yet just stopped playback details. I tried to brute force in the data from home_window.get_property('now_playing') But I didn't make much progress... It seemed to have some data, but it has not worked yet... And its getting late...

**Comment by mcarlton00** [comment]
Thanks for digging.  I'll do some poking around there and try to replicate it.

As an aside, I can give you a hint about debugging Kodi.  There's really two options

* Lots and lots of log messages
* web-pdb

It's a separate Kodi addon (https://kodi.wiki/view/Add-on:Web-PDB) that allows effectively pauses code execution and drops into a debugging session you can reach in your browser

**Comment by mcarlton00** [comment]
After several hours of digging of my own, I suspect you're on the right track.  `self.played_information` is never getting assigned data like it should be.  There's a few pieces to this, but to simplify what's happening:

* We're doing playback normally.  All is right with the world.
* `self.played_information` isn't being populated correctly (more on this later)
* When we stop playback, it tries to report that we've stopped.  But since that variable is empty, it never tells the server
* The server happily keeps chugging along assuming we're still playing for a period of time until it times us out.  A case could be made that this is an issue with the server ("I've stopped sending data to this client, I should also stop this playback session" type thinking), but alas, that's not how it currently works

So if that sequence of events is correct, then things make way more sense as to why stored playback gets ahead of where it should be.  It also makes _way_ more sense why I couldn't replicate this in the early days, because I would stop playback, immediately look at the server, and things were correct.  It's only reproducible when you stop playback and check on the server at least 30 minutes later.  From where I'm sitting, there's two different options on how to fix it.  Part of the reason this happened in the first place is that this particular section of code is kinda a mess of some things being in classes and some being standalone functions, and it makes it easy to lose data that's being passed around sometimes.  The "right" way to approach this would be to refactor stuff to rely almost all on classes, or almost all on standalone functions.  But that's a _lot_ of refactoring (this file is over 1200 lines currently).  So the easier solution is to just populate that variable (or a similar one) as items are added to the play queue, report them on playback finished, and make sure we remove them after they've been reported.  Otherwise that variable could grow indefinitely and potentially cause out of memory errors.  Because my time is somewhat limited, I'm going to go with option 2.  I should probably have time later this week/coming weekend to implement something that should work

**Comment by ltGuillaume** [comment]
Sounds plausible, thank you so much for digging into this, @Ozymandyaz and @mcarlton00 !!

On a side note, makes me wonder how and if the playback position is handled when you e.g. use an external player via the Android app: if it just passes the URI to the server, I guess it would exhibit the same behavior, if it would set up a local server to serve the file to the external app, I guess it could handle the playback position properly.

**Comment by ltGuillaume** [comment]
Thanks again for looking into this! 😃

**Comment by Ozymandyaz** [comment]
I gave this a try. and while it seems to report that playback has ended, Jellyfin does not retain any progress. i.e. if I start a show, watch 5 min and stop, Jellyfin sees the show as stopped but there is no progress on Jellyfin itself.

**Comment by Ozymandyaz** [comment]
Love to see the new updates and appreciate all the work!! But... As a followup now that 0.4.5 is out:

I have upgraded to 0.4.5+py3 on all three of my Kodi instances (including a fresh windows install today with no other plugins) and I have observed the following:

I see no change in behaviour for the "stopping" issue, i.e.  when I stop an episode in Kodi it continues to play in the Jellyfin dashboard. I have not done any tracing yet, but I will get web-pdb setup and see what I can find this weekend. 

Oddly, when I just copied over the play-utils.py with 0.4.4 before (see previous comment) I saw a different behaviour where the stream WOULD stop in the JF Dashboard, but no progress was recorded in JF and the episode was reset to the beginning.

And finally, with 0.4.5 I am seeing that, when an episode finishes, it does not appear to update its position in the next-up widget. That is to say, If I have five shows with a next up episode, and I play the third one all that way to the end, it will correctly update the widget to show the following episode in that series, but the series will remain in the third position. Its as if the last played time stamp is not updated, only progress. 

I have done zero troubleshooting short of setting up a fresh install with only estuary and Jellycon to confirm my findings. I see it in LibreElec x86, Windows 64 and Android TV (fire stick 4k) versions of Kodi/Jellycon

**Comment by mcarlton00** [comment]
I swear it was working, but you're right something isn't right now.  I'm getting a traceback when I start a file playing, which may be related.  Seems i may have typo'd something

**Comment by Ozymandyaz** [comment]
I grabbed the play_utils.py from #105 and everything is working great now, thanks for all the work on this!

**Comment by ltguillaume** [comment]
This behavior is again plaguing me, especially when Kodi 21/22alpha crashes (which in my case is _at least_ once every video I watch via JellyCon, on three different Windows systems, all of them issuing audio sync issues after the buffer expires somehow).

After restarting Kodi, in about 1/3 of the times, the resume point is 10-20 minutes further than the point up to which I watched the video, so same old thing. It can also be up to 30 minutes _before_ that point, so it's clear there's no periodical sync going on.
