### ISSUE TITLE
Play next episode dialog not working

### ISSUE THREAD

**Issue by Aelzki** [jellyfin/jellycon#70]
I am using this addon on Kodi 19 and it seems to have issues with prev and next episodes. What's the best version for jellyfin to use?

**Comment by mcarlton00** [comment]
It should always be compatible with the latest stable server release (currently 10.7.x).  To my knowledge, it's still compatible with 10.6.x as well, but I only follow stable for the most part.

What do you mean by next and previous episodes?

**Comment by Aelzki** [comment]
I'm sorry, I meant play next setting does not work on embuary/titan bingie mod (matrix) skin. when I set the following:
![image](https://user-images.githubusercontent.com/25884706/116768654-e333a500-aa6a-11eb-804c-0c6df579c99e.png)
When playing episodes, at the last 180 seconds or less, the dialouge does not appear (watch next episode).
