### ISSUE TITLE
Combine "In progress" and "Next up" as "Continue"

### ISSUE THREAD

**Issue by ltGuillaume** [jellyfin/jellycon#75]
I tend to create a favorite of "Next up", but at times Jellyfin doesn't see an episode as finished if the credits are a significant portion of it. As such, the (next episode of) the series won't show up at all in "Next up", because it's "stuck" under "In progress".

I think it would be a great solution to combine "In progress" and "Next up" into "Continue (watching)", instead of providing them separately. This would also remove the need to check "In progress" first, then "Next up", if you can't remember if you stopped half-way through an episode last time.

**Comment by mcarlton00** [comment]
I agree with the principle of joining them, but I worry that doing so now will break whatever shortcuts people may have set up.  It would need some thought first.  The options I see right now:

* Join them, have both previous sections point to the combined view
* Make it a user configurable setting
* Make it a third combined view and leave the two original view alone

**Comment by ltGuillaume** [comment]
I think the third option is the best in terms of compatibility: nothing breaks, nothing changes, just a useful extra item that is probably the easiest to implement, too.

Personally I'd go with the first option, but I think there might be use cases where combining the two into 20 items max. would not suffice for some people.

**Comment by quixventure** [comment]
I agree 100% on both counts.

There should be a combined list and it makes sense to make it a new item. 

However this behavior was introduced in 10.7.5 so its unlikely that anyone has config that depends on it.

**Comment by mcarlton00** [comment]
I would agree that having the In Progress stuff in front makes the most sense, and that's the same way I was thinking of implementing it.  @Ozymandyaz feel free to open a PR if you're comfortable sharing.

Apologies for being MIA for a while.  I recently bought a house and moved across town and have had a bunch of IRL stuff keeping me busy, so I just haven't had a bunch of dev time available.

**Comment by Ozymandyaz** [comment]
PR submitted, but please keep in mind that my Python skills consist of watching a YouTube video one day.... That being said... This works for me, and if anyone wants to hack it together the same way,  just edit widgets.py with the changes directly on your Kodi install...

**Comment by mcarlton00** [comment]
Closed by #82

**Comment by ltGuillaume** [comment]
I just updated to 0.4.5, but Next Up does not show any of the In Progress items...

I looked through the code, there doesn't seem to be an option that should be flicked, so what's going on?

I'm on Kodi 18.9

**Comment by mcarlton00** [comment]
It was added into the "widgets" function, but not the library folders.  `Addons -> JellyCon -> Custom Widgets`.

Probably should have been added to the other folders as well, but I didn't think about it at the time.

**Comment by ltGuillaume** [comment]
Aaah I get it. Yeah, that's rather confusing imho.
