### ISSUE TITLE
Error message while playing video in the background

### ISSUE THREAD

**Issue by Manuel5cc** [jellyfin/jellycon#76]
**Describe the bug**

Trying to play any video from the Jellyfin library works but an error message is displayed in front of the player saying "one or more elements failed to play"

**To Reproduce**

1. Go to the addon and play any video from the Jellyfin library.
2. An error message shows with the video in the background

**Expected behavior**

It should play the file without error messages

**Logs**

Attached below
[Log.txt](https://github.com/jellyfin/jellycon/files/6716540/Log.txt)

**Screenshots**

**System (please complete the following information):**
 - OS: Android 9
 - Jellyfin Version: 10.8.0
 - Kodi Version: 19.1
 - Addon Version: Last stable

**Additional context**

**Comment by mcarlton00** [comment]
Are you still seeing this?  And if so, can you get Kodi logs?  The server logs aren't overly helpful here.  https://kodi.wiki/view/Log_file/Easy
