### ISSUE TITLE
Playback not possible from "Show information" context menu

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellycon#77]
**Describe the bug**
When starting playback from the "Show information" context menu, the playback fails/stops after about a second. I would guess this is related to #66. If I leave the default to "Play", playback works normally.

**To Reproduce**
1. Set default action to "Show information"
2. Set up a widget for JellyCon in a skin (using Arctic Zephyr Reloaded personally)
3. Click on item, see information and press play
4. Item starts playback but stops in about a second

**Expected behavior**
Playback continues.

**Logs**
I'm running Kodi on androidtv so I don't have the ability to gather logs currently. Should be easy enough to reproduce though. If you need them just let me know and I'll see what I can do.

**System (please complete the following information):**
 - OS: Android tv
 - Jellyfin Version: 10.7.6
 - Kodi Version: 19.1
 - Addon Version: 0.4.4

**Comment by mcarlton00** [comment]
I'm able to replicate this.  Interestingly, if we step through the code line by line then playback starts fine.  So it seems like it's a race condition of some kind causing conflicts

**Comment by Queuecumbr** [comment]
Is there any update on this? I am also experiencing this issue.

**System:**
- Device: NVIDIA Shield TV Pro
- OS: Android TV 9.0.0. / Shield Experience 8.2.3
- Jellyfin Version: 10.7.7-1 (Debian 11)
- Kodi Version: 19.3
- Skin: Embuary
- Add-on Version: 0.4.7

**Comment by mcarlton00** [comment]
Unfortunately not yet.  I'm seeing it too, but it doesn't make sense.  The api calls and the commands sent to Kodi appear to be identical, but it's almost like the play command is handled differently between a normal play action and an info menu play action within kodi itself.  When I walk through the code bit by bit playback wouldn't fail until after the addon finished executing code
