### ISSUE TITLE
Album track sorting incorrect

### ISSUE THREAD

**Issue by krruzic** [jellyfin/jellycon#79]
When I view an album, the song order is all out of whack. Sort is set to track number but it clearly isn't following that. The first screenshot shows how it is in the jellyfin web UI (what I want) bottom is the order in kodi.
![jellycon2](https://user-images.githubusercontent.com/4000854/128791510-fd2a8299-1be3-4cc8-b6ff-bd5072c66c73.png)
![jellycon1](https://user-images.githubusercontent.com/4000854/128791513-534acd47-ce1a-46b2-b7bc-1b03a5364570.png)

**Comment by mcarlton00** [comment]
I can replicate this, but unfortunately I haven't found what the issue is yet.  Kodi's api appears to have different parameters we can choose to sort from, but it's straight up ignoring the metadata I'm passing in.  It seems like none of the sort options are working properly in my testing.

**Comment by krruzic** [comment]
Thank you for the fix!! I investigated myself and ran into what you described in your comment, how did you trace down the bug to the Cast being present?

**Comment by mcarlton00** [comment]
Several hours of cursing, followed by giving up and deleting code until it started working as expected.  I had made a super simple dummy plugin to make sure the behavior wasn't broken in kodi itself, so I knew it had to be something we were doing here.
