### ISSUE TITLE
No compatibility matrix, though dependencies point to minimum Kodi version of Krypton or higher?

### ISSUE THREAD

**Issue by surfrock66** [jellyfin/jellycon#97]
**Describe the bug**
I have a very old Odroid C1 running openelec based on Kodi Jarvis.  I am trying to install jellycon like I have on newer micro-board based media servers and am not able to install due to failed dependency resolution.

**To Reproduce**
1. Add jellyfin kodi repository to sources
2. Browse add-ons, find none
3. Go to install add-on from Zip with the source being the jellyfin repository
4. Try to install a jellycon zip

**Expected behavior**
The add-on installs

**Logs**
17:34:34 T:2551305104   ERROR: CAddonInstallJob[plugin.video.jellycon]: The dependency on script.module.requests version 2.22.0 could not be satisfied.

**System (please complete the following information):**
 - OS: Raspbian
 - Jellyfin Version: 10.7.7
 - Kodi Version: 16.1 (Openelec 7.0.0)
 - Addon Version: any 2-4

**Comment by mcarlton00** [comment]
Typically, we try to support the current release -1.  Right now, that's Kodi 19 (currently) and 18 (previous 1).  I believe 17 is currently working, but that's not by any extra effort on our part.  We only have easy access to 18 and 19 for development.  Kodi 16 won't work for multiple reasons, the biggest of which is dependency issues and API changes.  As you've seen, we're using at least Krypton dependencies for most things,  And at least one of our dependencies (websockets) isn't available in Jarvis at all.

I've gotta be blunt, Jarvis is _ancient_.  It's last release was in 2016.  There's just no feasible way for us to consistently support 4 major versions of Kodi.  It's unfortunate, but sometimes hardware becomes too old to be useful.  For this use case, at least.
